<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Liste paginée
     * @param $page
     * @param $nbPerPage
     * @return Paginator
     */
    public function getPaginatedResult($page, $nbPerPage)
    {

        $query = $this->createQueryBuilder('data');


        $query
            //->orderBy('data.dateTraitement', 'ASC')
            ->orderBy('data.nom', 'ASC')
            ->setFirstResult(($page - 1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
            ->getQuery()
        ;

        return new Paginator($query, false);
    }

    public function getNbResult($search)
    {

        $query = $this->createQueryBuilder('data')
          /*->leftJoin("data.statutRappel", "statutRappel")
          ->addSelect('statutRappel')
          ->leftJoin("data.origineRappel", "origineRappel")
          ->addSelect('origineRappel')*/
        ;

        /*if(isset($search['dateRappel']) && $search['dateRappel'] != ''){
            $date = date_create_from_format('Y-m-d',$search['dateRappel']);
            $query = $query->andWhere('data.dateRappel >= :date_start')
              ->andWhere('data.dateRappel <= :date_end')
              ->setParameter('date_start', $date->format('Y-m-d 00:00:00'))
              ->setParameter('date_end', $date->format('Y-m-d 23:59:59'));
        }

        if(isset($search['dateCreation']) && $search['dateCreation'] != ''){
            $date = date_create_from_format('Y-m-d',$search['dateCreation']);
            $query = $query->andWhere('data.dateCreation >= :date_start')
              ->andWhere('data.dateCreation <= :date_end')
              ->setParameter('date_start', $date->format('Y-m-d 00:00:00'))
              ->setParameter('date_end', $date->format('Y-m-d 23:59:59'));
        }

        $query = $query->andWhere('statutRappel.id = 1');

        if($search['origineRappel'] != ''){
            $query = $query->andWhere('origineRappel.id = :origine')
              ->setParameter('origine', $search['origineRappel']);
        }*/


        $query = $query
            ->getQuery()
        ;

        return $query->getResult();
    }
}
