app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_base:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app_coach:
    resource: "@GestionBundle/Resources/config/routing.yml"
    prefix:   /coach

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"