# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_PS:          ROLE_PS
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_PS,ROLE_USER,ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:   ^/
            host: dietycoach.fr
            anonymous: true
            provider:  fos_userbundle
            form_login:
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                remember_me: true
            remember_me:
                secret: "%secret%"
                lifetime: 504000 # in seconds
                remember_me_parameter: _remember_me

            logout:
                path:   fos_user_security_logout
                target: /admin
                invalidate_session: false
            switch_user: { role: ROLE_SUPER_ADMIN }

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, role: [ ROLE_ADMIN ] }
        - { path: ^/admin/utilisateurs$, role: [ ROLE_ADMIN ] }
        - { path: ^/admin/coach, role: [ ROLE_ADMIN ] }
        - { path: ^/admin/codes, role: [ ROLE_ADMIN ] }
        - { path: ^/admin/coach/$, role: [ ROLE_ADMIN ] }
        - { path: ^/admin/codes/$, role: [ ROLE_ADMIN ] }
        #- { path: ^/$, role: [ ROLE_USER, ROLE_PS, ROLE_ADMIN ] }
        #- { path: ^/agenda, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/gestion, role: [ ROLE_PS ] }
        #- { path: ^/admin, role: [ ROLE_ADMIN ] }